### ISSUE TITLE
Is an AppImage available for download?

### ISSUE THREAD

**Issue by probonopd** [brittonhayes/pod#5]
Is an AppImage available for download? If so, we'd like to add it to https://github.com/AppImage/appimage.github.io.
Thanks.

**Comment by brittonhayes** [comment]
Hey there @probonopd! Thanks for reaching out. I've just fixed the release action to include an `AppImage` of pod :slightly_smiling_face: 

I'll update this issue when I've confirmed that's working successfully.

**Comment by brittonhayes** [comment]
@probonopd As of [v0.7.6](https://github.com/brittonhayes/pod/releases/tag/v0.7.6), an AppImage is distributed in the application release. Would love to see pod added to [appimage.github.io](https://github.com/AppImage/appimage.github.io)! :heart: 

The application is still very early beta and does not contain all functionality, but I'm slowly chipping away at it. And nevertheless, it does now and will continue to fully support AppImage.
